-- Canonical sensor telemetry schema.
-- Run this before rbac_setup.sql. The ESP32 writes one atomic five-minute
-- statistical snapshot to sensor_history; every consumer reads the same row.

create table if not exists public.sensor_history (
  id bigint generated by default as identity primary key,
  recorded_at timestamptz not null default now(),
  avg_ph numeric not null,
  median_ph numeric not null,
  min_ph numeric not null,
  max_ph numeric not null,
  latest_ph numeric not null,
  std_ph numeric not null default 0,
  avg_ec numeric not null,
  median_ec numeric not null,
  min_ec numeric not null,
  max_ec numeric not null,
  latest_ec numeric not null,
  std_ec numeric not null default 0,
  avg_temp numeric not null,
  median_temp numeric not null,
  min_temp numeric not null,
  max_temp numeric not null,
  latest_temp numeric not null,
  std_temp numeric not null default 0,
  sample_count integer not null check (sample_count > 0)
);

create index if not exists sensor_history_recorded_at_idx
on public.sensor_history (recorded_at desc);

alter table public.sensor_history enable row level security;

-- The ESP32 uses the publishable key. It may insert telemetry but may not
-- update or delete it. Authenticated application users may read telemetry.
grant insert on table public.sensor_history to anon;
grant select on table public.sensor_history to authenticated;
do $$
begin
  if to_regclass('public.sensor_history_id_seq') is not null then
    grant usage, select on sequence public.sensor_history_id_seq to anon;
  end if;
end $$;

drop policy if exists "Sensor can insert history" on public.sensor_history;
create policy "Sensor can insert history"
on public.sensor_history for insert to anon
with check (
  avg_ph between 0 and 14
  and avg_ec between 0 and 20
  and avg_temp between -20 and 80
  and sample_count between 1 and 120
);

drop policy if exists "Authenticated users can read sensor history" on public.sensor_history;
create policy "Authenticated users can read sensor history"
on public.sensor_history for select to authenticated using (true);

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'sensor_history'
  ) then
    alter publication supabase_realtime add table public.sensor_history;
  end if;
end $$;

-- Legacy tables are intentionally not created here. After the unified app and
-- ESP32 are deployed, these become deletion candidates after backup review:
-- ph_readings, ec_readings, temp_readings, critical_alerts, history_logs.
